### ISSUE TITLE
Implement `TryFrom<std::fs::Metadata>` for `remotefs::fs::Metadata`

### ISSUE THREAD

**Issue by ok-nick** [veeso/remotefs-rs#11]
Should be an understandable change, it removes a lot of boilerplate when calling the `create` method of `RemoteFs`.

**Comment by veeso** [comment]
Implemented in 0.2.0 branch. Actually, I opted for `From` instead of `TryFrom`, here's the reason: it's true that when accessing to times, the getter may fail if the requested data is not supported on the current system, but it would really be a hustle to deal with it.

For example: on UNIX based systems, created() will always return an error. That's because those systems won't record the created time for files. This means that whenever I get a stdlib metadata from a remote server, the try from would fail in case the data comes from a Linux server, but wouldn't fail when received from a windows server. I can imagine that this would be kinda hard to handle for a user.

So I think the best option here, is to return ok().unwrap_or(UNIX_EPOCH).

**Comment by ok-nick** [comment]
I think it would be best to keep fields like `created` as an option. It should be up to the user to decide on how they want to handle missing timestamps. Think about a case where the user wants to display a UI representing the creation timestamp of a specified file. Well, it would say the file was created in 1970 which would be very odd.

**Comment by veeso** [comment]
Yeah, keeping times as an option is a great idea tbh
