### ISSUE TITLE
More explicit naming

### ISSUE THREAD

**Issue by ok-nick** [veeso/remotefs-rs#4]
I think this kind of goes off my last issue with the solution being follow how the `std` behaves, but the ultimate goal here is to have the `Metadata` struct very similar to `std::fs::Metadata`. Rather than the undescriptive `atime`, `ctime`, `gid`, etc, it could be abstracted into a `Permissions` struct, or a `created`/`modified`/`accessed` method. To take this a step further, you could even implement some of the `MetadataExt` traits for platform-specific code/namings, although I don't think it makes much sense since it's over a network protocol.

**Comment by veeso** [comment]
I changed the time attributes to `accessed`, `created` and `modified` as in `Metadata`. I won't change `gid`, `uid` and `mode`, since are named like that in the `MetadataExt` struct. It wouldn't make much sense to create a metadata ext here too since 99% of the servers run on POSIX machine anyways, so I wouldn't make it that complex. Anyway, those attributes are optional.
